[build]
  publish = "."
  command = ""

# === Pretty URLs ===

[[redirects]]
  from = "/login"
  to = "/login/login.html"
  status = 200

[[redirects]]
  from = "/driver/dashboard"
  to = "/dashboard/driver/driver-dashboard.html"
  status = 200

[[redirects]]
  from = "/driver/profile"
  to = "/profile/driver/driver-profile.html"
  status = 200

[[redirects]]
  from = "/add-car"
  to = "/car/add-car.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile/client/client-profile.html"
  status = 200

[[redirects]]
  from = "/route/credentials"
  to = "/route/route-credentials.html"
  status = 200

[[redirects]]
  from = "/qr-scan"
  to = "/order/qr-code.html"
  status = 200

[[redirects]]
  from = "/client/profile"
  to = "/profile/client/client-profile.html"
  status = 200

[[redirects]]
  from = "/orders/new-order"
  to = "/order/order-create.html"
  status = 200

[[redirects]]
  from = "/orders"
  to = "/order/orders.html"
  status = 200

[[redirects]]
  from = "/add-route"
  to = "/route/add-route.html"
  status = 200

[[redirects]]
  from = "/banner"
  to = "/banner-info.html"
  status = 200

[[redirects]]
  from = "/set-credentials"
  to = "/login/set-credentials.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/client/dashboard"
  to = "/dashboard/client/client-dashboard.html"
  status = 200

[[redirects]]
  from = "/routes"
  to = "/route/routes.html"
  status = 200

# === API Proxy ===
[[redirects]]
  from = "/api/*"
  to = "https://api.rout24.online/:splat"
  status = 200
  force = true

# === SPA fallback (optional) ===
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
